export const COLOURS = {
    white: '#ffffff',
    black: '#000000',
    lightGray: '#B3B4B6',
    accent: '#FFC231',
    accentRed: '#FB5D2E',
    accentPink: '#F96165',
  };

  export const Categories = [
    {
      name: 'Burger',
      image: require('../database/images/burger.png'),
      items: [
        {
          id:1,
          name: 'Classic Burger',
          weight: 120,
          rating: '5.0',
          price: 199,
          isTopOfTheWeek: true,
          image: require('../database/images/burger/classicburger.png'),
          size: 'Large 8"',
          crust: 'Thick Crust',
          delivery: 25,
          ingredients: [
            require('../database/images/flour.png'),
            require('../database/images/cheese.png'),
            require('../database/images/Sliced-Onion.png'),
            require('../database/images/Tomato.png'),
          ],
        },
        {
          id:2,
          name: 'Aloo Tikki Burger',
          weight: 150,
          rating: '4.5',
          price: 99,
          isTopOfTheWeek: false,
          image: require('../database/images/burger/alootikkiburger.png'),
          size: 'Large 12"',
          crust: 'Thick Crust',
          delivery: 20,
          ingredients: [
            require('../database/images/Sliced-Onion.png'),
            require('../database/images/Tomato.png'),
            require('../database/images/cheese.png'),
            require('../database/images/flour.png'),
          ],
        },
        {
          id:3,
          name: 'Biggie Cheese',
          weight: 250,
          rating: '4.2',
          price: 299,
          isTopOfTheWeek: false,
          image: require('../database/images/burger/biggiecheese.png'),
          size: 'Large 10"',
          crust: 'Thick Crust',
          delivery: 35,
          ingredients: [
            require('../database/images/Tomato.png'),
            require('../database/images/cheese.png'),
            require('../database/images/Sliced-Onion.png'),
            require('../database/images/flour.png'),
          ],
        },
      ],
    },
    {
      name: 'Pizza',
      image: require('../database/images/pizza.png'),
      items: [
        {
          id:4,
          name: 'Pepperoni Pizza',
          weight: 250,
          rating: '5.0',
          price: 199,
          isTopOfTheWeek: true,
          image: require('../database/images/pizza/pepperonipizza.png'),
          size: 'Large 14"',
          crust: 'Thin Crust',
          delivery: 30,
          ingredients: [
            require('../database/images/Tomato.png'),
            require('../database/images/cheese.png'),
            require('../database/images/Sliced-Onion.png'),
            require('../database/images/flour.png'),
          ],
        },
        {
          id:5,
          name: 'Plain Cheese Pizza',
          weight: 300,
          rating: '4.5',
          price: 299,
          isTopOfTheWeek: false,
          image: require('../database/images/pizza/plaincheesepizza.png'),
          size: 'Large 16"',
          crust: 'Thin Cheese',
          delivery: 25,
          ingredients: [
            require('../database/images/Sliced-Onion.png'),
            require('../database/images/flour.png'),
            require('../database/images/cheese.png'),
            require('../database/images/Tomato.png'),
          ],
        },
        {
          id:6,
          name: 'Mexican Green Wave',
          weight: 350,
          rating: '4.2',
          price: 499,
          isTopOfTheWeek: false,
          image: require('../database/images/pizza/mexicangreenwave.png'),
          size: 'Large 15"',
          crust: 'Thin Crust',
          delivery: 45,
          ingredients: [
            require('../database/images/flour.png'),
            require('../database/images/cheese.png'),
            require('../database/images/Tomato.png'),
            require('../database/images/Sliced-Onion.png'),
          ],
        },
      ],
    },
    {
      name: 'Soft Drinks',
      image: require('../database/images/softdrinks.png'),
      items: [
        {
          id:7,
          name: 'Coco Cola',
          weight: 200,
          rating: '5.0',
          price: 299,
          isTopOfTheWeek: true,
          image: require('../database/images/softdrinks/cocacola.png'),
          size: 'Medium Glass',
          crust: 'Small Ice',
          delivery: 10,
          ingredients: [require('../database/images/softdrinks/cocacola.png')],
        },
        {
          id:8,
          name: 'Orange Juice',
          weight: 500,
          rating: '4.5',
          price: 199,
          isTopOfTheWeek: false,
          image: require('../database/images/softdrinks/orange.png'),
          size: 'LArge Glass',
          crust: 'Large Ice',
          delivery: 8,
          ingredients: [require('../database/images/softdrinks/orange.png')],
        },
        {
          id:9,
          name: 'Mango Juice',
          weight: 150,
          rating: '4.2',
          price: 99,
          isTopOfTheWeek: false,
          image: require('../database/images/softdrinks/mango.png'),
          size: 'Large Glass',
          crust: 'Small Ice',
          delivery: 5,
          ingredients: [require('../database/images/softdrinks/mango.png')],
        },
      ],
    },
  ];


  export const Items=[
    
      {
        id:1,
        category:'burger',
        name: 'Classic Burger',
        weight: 120,
        rating: '5.0',
        price: 199,
        isTopOfTheWeek: true,
        image: require('../database/images/burger/classicburger.png'),
        size: 'Large 8"',
        crust: 'Thick Crust',
        delivery: 25,
        ingredients: [
          require('../database/images/flour.png'),
          require('../database/images/cheese.png'),
          require('../database/images/Sliced-Onion.png'),
          require('../database/images/Tomato.png'),
        ],
      },
      {
        id:2,
        category:'burger',
        name: 'Aloo Tikki Burger',
        weight: 150,
        rating: '4.5',
        price: 99,
        isTopOfTheWeek: false,
        image: require('../database/images/burger/alootikkiburger.png'),
        size: 'Large 12"',
        crust: 'Thick Crust',
        delivery: 20,
        ingredients: [
          require('../database/images/Sliced-Onion.png'),
          require('../database/images/Tomato.png'),
          require('../database/images/cheese.png'),
          require('../database/images/flour.png'),
        ],
      },
      {
        id:3,
        category:'burger',
        name: 'Biggie Cheese',
        weight: 250,
        rating: '4.2',
        price: 299,
        isTopOfTheWeek: false,
        image: require('../database/images/burger/biggiecheese.png'),
        size: 'Large 10"',
        crust: 'Thick Crust',
        delivery: 35,
        ingredients: [
          require('../database/images/Tomato.png'),
          require('../database/images/cheese.png'),
          require('../database/images/Sliced-Onion.png'),
          require('../database/images/flour.png'),
        ],
      },
      {
        id:4,
        category:'pizza',
        name: 'Pepperoni Pizza',
        weight: 250,
        rating: '5.0',
        price: 199,
        isTopOfTheWeek: true,
        image: require('../database/images/pizza/pepperonipizza.png'),
        size: 'Large 14"',
        crust: 'Thin Crust',
        delivery: 30,
        ingredients: [
          require('../database/images/Tomato.png'),
          require('../database/images/cheese.png'),
          require('../database/images/Sliced-Onion.png'),
          require('../database/images/flour.png'),
        ],
      },
      {
        id:5,
        category:'pizza',
        name: 'Plain Cheese Pizza',
        weight: 300,
        rating: '4.5',
        price: 299,
        isTopOfTheWeek: false,
        image: require('../database/images/pizza/plaincheesepizza.png'),
        size: 'Large 16"',
        crust: 'Thin Cheese',
        delivery: 25,
        ingredients: [
          require('../database/images/Sliced-Onion.png'),
          require('../database/images/flour.png'),
          require('../database/images/cheese.png'),
          require('../database/images/Tomato.png'),
        ],
      },
      {
        id:6,
        category:'pizza',
        name: 'Mexican Green Wave',
        weight: 350,
        rating: '4.2',
        price: 499,
        isTopOfTheWeek: false,
        image: require('../database/images/pizza/mexicangreenwave.png'),
        size: 'Large 15"',
        crust: 'Thin Crust',
        delivery: 45,
        ingredients: [
          require('../database/images/flour.png'),
          require('../database/images/cheese.png'),
          require('../database/images/Tomato.png'),
          require('../database/images/Sliced-Onion.png'),
        ],
      },
      {
        id:7,
        category:'soft',
        name: 'Coco Cola',
        weight: 200,
        rating: '5.0',
        price: 299,
        isTopOfTheWeek: true,
        image: require('../database/images/softdrinks/cocacola.png'),
        size: 'Medium Glass',
        crust: 'Small Ice',
        delivery: 10,
        ingredients: [require('../database/images/softdrinks/cocacola.png')],
      },
      {
        id:8,
        category:'soft',
        name: 'Orange Juice',
        weight: 500,
        rating: '4.5',
        price: 199,
        isTopOfTheWeek: false,
        image: require('../database/images/softdrinks/orange.png'),
        size: 'LArge Glass',
        crust: 'Large Ice',
        delivery: 8,
        ingredients: [require('../database/images/softdrinks/orange.png')],
      },
      {
        id:9,
        category:'soft',
        name: 'Mango Juice',
        weight: 150,
        rating: '4.2',
        price: 99,
        isTopOfTheWeek: false,
        image: require('../database/images/softdrinks/mango.png'),
        size: 'Large Glass',
        crust: 'Small Ice',
        delivery: 5,
        ingredients: [require('../database/images/softdrinks/mango.png')],
      },
  

  ]